### ISSUE TITLE
Addition of Hugo CLI Package

### ISSUE THREAD

**Issue by harleywelsby** [vecnz/Website#62]
Currently you need to install Hugo to run the site locally for dev work, but we could use this: https://www.npmjs.com/package/hugo-cli in the devDependencies to run using the existing scripts with no extra installs outside of NPM. Would be much easier for new people helping out on the site.

Latest version uses a vulnerable version of Got though (https://www.npmjs.com/package/got), so we'd have to bump that in package-lock to `12.x.x`.

Works on my local but I don't have permissions to the vecnz org to create branches/PRs in this repo. Keen to implement this myself if someone can give me perms.

**Comment by Darkflame72** [comment]
Are you able to fork the repo and open a pr from that?

**Comment by harleywelsby** [comment]
Ah yep got it, cheers. Put up a PR here: https://github.com/vecnz/Website/pull/63
